### ISSUE TITLE
Version 1.11.1 is not SSR compatible (Using Nuxt)

### ISSUE THREAD

**Issue by antony** [antoniandre/vueper-slides#10]
Installing 1.11.1 (via the method described in #9) results in a `document not defined` error in nuxt:

```js
   return component;
  }
  /* style inject */
  function __vue_create_injector__$1() {
    var head = document.head || document.getElementsByTagName('head')[0];
    var styles = __vue_create_injector__$1.styles || (__vue_create_injector__$1.styles = {});
    var isOldIE = typeof navigator !== 'undefined' && /msie [6-9]\\b/.test(navigator.userAgent.toLowerCase());

    return function addStyle(id, css) {
      if (document.querySelector('style[data-vue-ssr-id~="' + id + '"]')) return; // SSR styles are present.            
```

**Comment by antoniandre** [comment]
Hi @antony, 
Please tell about your environment, is it Nuxt as you were using before?
Have you followed steps in https://github.com/antoniandre/vueper-slides/issues/6?
Have you updated Nuxt or other dependencies which could be the cause?


I just updated Vueper Slides in a testing Nuxt environment using `npm i --save-dev vueperslides`, everything is working as expected, I can even play with the new feature multiple visible slides 👌

Just to make sure I also updated Nuxt by running `npm install --save nuxt`: no problem on latest Nuxt version 1.4.2 neither.

So it must come from your config.

Please try installing a fresh new Nuxt with Vueper Slides and use `<no-ssr>` wrapping tag.

Also please note that the package name is `vueperslides` not `vueper-slides`.

**Comment by antony** [comment]
Thanks for your quick feedback. Busy day but I'll try to provide an example tomorrow!

**Comment by Resoguy** [comment]
I have ran into same error but as @antoniandre said no-ssr tag made it. Now it works. Thanks @antoniandre.

**Comment by antony** [comment]
Can confirm this is the case - but the reason I chose this library over others is SSR compatibility, so it's a shame if I have to start using no-ssr tags :(

**Comment by antoniandre** [comment]
By using the `no-ssr` tag you have solved the issue.
for your last request: SSR support, please refer to this issue: https://github.com/antoniandre/vueper-slides/issues/13.
