### ISSUE TITLE
Visible - Invisible =) 

### ISSUE THREAD

**Issue by cvaize** [antoniandre/vueper-slides#101]
![image](https://user-images.githubusercontent.com/26907947/87789637-cb32c200-c858-11ea-9896-0f369c9ab387.png)
![image](https://user-images.githubusercontent.com/26907947/87789428-7b53fb00-c858-11ea-89b8-9ebea6d8bf04.png)
![image](https://user-images.githubusercontent.com/26907947/87789553-ab9b9980-c858-11ea-93b2-5e329647dd94.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/87791397-970cd080-c85b-11ea-8737-86b38f4f9387.png)

**Comment by antoniandre** [comment]
Hi @cvaize,

Thanks for your feedback but I'm sorry I don't understand the question. 😅
Not sure if you can speak english but at worse you can Google translate your question into English so I can help you!

**Comment by cvaize** [comment]
Pay attention to the last screenshot, the first slide that is shown is marked as hidden =)

**Comment by cvaize** [comment]
https://cromi.ru/arenda-turgidov

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/91708089-426aae00-eb9a-11ea-8cff-2e6ec6db9c61.png)

**Comment by antoniandre** [comment]
Thanks for the reproduction link, I can see the problem now. 
Will let you know when fixed!

**Comment by cvaize** [comment]
Thank You =)

**Comment by antoniandre** [comment]
Hi @cvaize, this is now fixed in version 2.10.7.
Observable on the 2nd example of this documentation link: https://antoniandre.github.io/vueper-slides/#ex--show-multiple-slides-and-gap

Hope it helps.

**Comment by cvaize** [comment]
Thank you, the error has been fixed.
