### ISSUE TITLE
<vueper-slides :infinite="false" has no effect

### ISSUE THREAD

**Issue by rucebee** [antoniandre/vueper-slides#102]
When setting :infinite="false": on the last slide Arrow RIght is still active and leads to the first slide

"vueperslides": "^2.10.2"
 -and example page-
https://antoniandre.github.io/vueper-slides/#ex--arrows-and-bullets

**Comment by rucebee** [comment]
Same misbehaviour  on the first slide

**Comment by antoniandre** [comment]
Hi @rucebee sorry for late reply.
This is intended, disabling the arrow on edge is an option: `disableArrowsOnEdges`, you can find it in the API section (https://antoniandre.github.io/vueper-slides/#vueper-slides--api).
You can also see it in action in this example: https://antoniandre.github.io/vueper-slides/#ex--add-remove-slides--disable

Hope it helps.

**Comment by rucebee** [comment]
@antoniandre, thank you so much for explanation of _infinite_ / _disableArrowsOnEdges_ options and nice API guide

I intuitively used _infinite_ only to "disable arrows on edges" and that was my mistake
