### ISSUE TITLE
Arrows with slideMultiple not advancing or reversing slide direction on first click

### ISSUE THREAD

**Issue by yhtomitim** [antoniandre/vueper-slides#108]
When displaying 5 slides at a time, a user must click the right arrow to advance the slides to the right 2x to get the slides to update. This appears to be because the method to slide the slides over doesn't fire until the currentSlide appears to be near the middle. I think the expected behavior in this context would be advance the slides 1 on click when showing multiple regardless of what slide is active.  Here're the methods I'm using on the component.

```        <vueper-slides
          class="no-shadow"
          autoplay
          :touchable="false"
          :pause-on-hover="true"
          :fixed-height="true"
          :bullets="false"
          :visibleSlides="5"
          :gap="1"
          arrows-outside
          :breakpoints="breakpoints">```

**Comment by antoniandre** [comment]
Hi @yhtomitim,
Could you do a Codepen repro with your full code? That will be helpful.
You can fork this Codepen to start with: https://codepen.io/antoniandre/pen/jevjoQ.
Thanks.

**Comment by antoniandre** [comment]
Closing the issue due to inactivity. Please reopen if not solved.
