### ISSUE TITLE
Click handler inside a slide

### ISSUE THREAD

**Issue by matejmachac** [antoniandre/vueper-slides#11]
Is there a possibility to make click handlers work inside a single slide?

If not, do you have a workaround for this?

Thanks.

**Comment by matejmachac** [comment]
Hi @antoniandre,
we need to have either a vue router link, or a div with a click handler. Is there a way to do this?

**Comment by antoniandre** [comment]
You can place a router link in any slide by using https://antoniandre.github.io/vueper-slides/#ex--complex-slide-title-and-content.

Then if you need to make the entire slide clickable you can position it absolute in CSS for instance.

**Comment by af-mma** [comment]
@antoniandre we will try to implement this, thanks. Doesn't this create a potential problem with touch swiping on mobile, though (clickable div covering the entire slide)?

**Comment by matejmachac** [comment]
@antoniandre we will try to implement this, thanks. Doesn't this create a potential problem with touch swiping on mobile, though (clickable div covering the entire slide)?

**Comment by matejmachac** [comment]
@antoniandre Thanks for your help, we have implemented the "complex slide solution" and it works well for our use case.
