### ISSUE TITLE
Feature Request: Youtube Embed video

### ISSUE THREAD

**Issue by puzant** [antoniandre/vueper-slides#110]
I like this library so much, will it be possible in the future to add a youtube embed video in the slides

**Comment by antoniandre** [comment]
Hi @puzant, thanks for your feedback and suggestion.
I agree this would be a nice feature, I will work on that soon.

**Comment by antoniandre** [comment]
Hi @puzant, @alexdohmen,

The feature is now available in version 2.12.0
https://antoniandre.github.io/vueper-slides/#ex--videos

Hope it helps!

**Comment by antoniandre** [comment]
Closing the issue now, please reopen if you find any problem!
