### ISSUE TITLE
Support Vue 3

### ISSUE THREAD

**Issue by RichPC** [antoniandre/vueper-slides#111]
Looks like a great slideshow component, but I've no idea how much work it'd take to support Vue3?  I've tried installing it and importing the same way as Vue2 but, it's throwing errors from vuperslides.common.js at line 4143

var render = function etc

vueperslides.common.js?b1b5:4143 Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

**Comment by KEVDEVR** [comment]
Same Problem.

**Comment by antoniandre** [comment]
Hi @RichPC, @KEVDEVR, 
Thanks for your feedback. I've migrated my other libs to Vue 3 already so I know it's possible.
It's not so straightforward, so I was kinda waiting for someone to ask for it on Vueper Slides lol.

I'll start it soon and will let you know guys.

**Comment by RichPC** [comment]
Thanks for even offering, good luck. I had a look on awesome vue 3 and
there's only one lightweight slideshow in the list at the moment.

Regards,
Richard Creek

**Comment by antoniandre** [comment]
Hi @RichPC, @KEVDEVR, 
Good news, Vueper Slides is not on Vue 3!

To install, run `npm i vueperslides@next` (this version is not compatible with Vue 2).

Here's a demo on Vue 3.
https://codepen.io/antoniandre/pen/xxOgGEK?editors=1010

Hope it helps, please close the issue if working as expected. :)

**Comment by RichPC** [comment]
Thanks @antoniandre,

That looks to be working really well.
