### ISSUE TITLE
rtl version

### ISSUE THREAD

**Issue by roussafi-omar** [antoniandre/vueper-slides#113]
we want an rtl version plllllllllllz

**Comment by antoniandre** [comment]
Hi @roussafi-omar,

Good news, I added the RTL support, check it out on this example:
https://codepen.io/antoniandre/pen/ZEORWYv

to make it work: add the `rtl` option on the `vueper-slides` tag, and have an rtl context (e.g. `html {direction: rtl;}`).

Hope it helps!

**Comment by antoniandre** [comment]
Now available, closing the issue. Please reopen if not solved.
