### ISSUE TITLE
Since 2.11.0 the arrow slots aren't working

### ISSUE THREAD

**Issue by Dev-Oli** [antoniandre/vueper-slides#116]
The arrow slots aren't working anymore using the latest vueper-slide release but showing the default arrows instead, see the following sample: https://codepen.io/DevMaxDev/pen/qBNQQZy

If you downgrade to 2.10.9 the custom slots are used as expected instead of the default arrows.

**Comment by antoniandre** [comment]
Hi @Dev-Oli,
Thanks for reporting, I forgot to put back the arrows slots after adding the new RTL feature, I initially intended to rename the slots then I changed my mind.

I just release version 2.12.1 that should fix this.

**Comment by Dev-Oli** [comment]
Thanks for the patch. I can confirm that the arrow slots are working again.
