### ISSUE TITLE
Dragging by hand isn't working

### ISSUE THREAD

**Issue by aalicki** [antoniandre/vueper-slides#121]
**Problem:**
I'm attempting to drag the slider left or right, by clicking the mouse on an image / slide, but the slider isn't reacting. Even if using examples directly from the demos, I'm unable to get this functionality to work.

**Expectations:**
For the slider to move in the direction I'm dragging my cursor while clicked on.

**Vue.js Version:** 2.5.17
**Vueper Version:** 2.10.8

Code Example:
```
<vueper-slides
            :touchable="true"
            :dragging-distance="70"
            :slide-ratio="1 / 4"
            class="no-shadow"
            :visible-slides="4"
            slide-multiple
            :gap="3"
            :breakpoints="breakpoints"
        >
            <vueper-slide v-for="(slide, i) in slides"
                          :key="i"
                          :image="image_url.jpg"
                          :content="Test Content"
                          :link="google.com" />
            </vueper-slide>
        </vueper-slides>
```

Breakpoints:
```
breakpoints: {
            1200: {
                slideRatio: 1 / 5
            },
            900: {
                slideRatio: 1 / 3
            },
            600: {
                slideRatio: 1 / 2,
                arrows: false,
                bulletsOutside: true
            },
            // The order you list breakpoints does not matter, Vueper Slides will sort them for you.
            1100: {
                slideRatio: 1 / 4
            }
        },
```

**Comment by aalicki** [comment]
@mdivani - No, I'm trying to work through the issues, assuming it's related to CSS. I've been exploring other sliders in the meantime since the drag-by-hand is fairly important on smaller devices.

**Comment by antoniandre** [comment]
Hi @aalicki, @mdivani,
Sorry I've been relocating.

Not sure I understand the issue, can you click and drag the slides in this basic Codepen https://codepen.io/antoniandre/pen/YzGNdYp?editors=1010 ? 

If not what is your OS and browser please?

**Comment by antoniandre** [comment]
Closing the issue due to inactivity. I let you reopen if you have some details and/or reproduction link!
