### ISSUE TITLE
Remove Slides from random positions

### ISSUE THREAD

**Issue by abhijithbabu** [antoniandre/vueper-slides#122]
Hi,

is there a way to remove slides not from end but from any position? I tried doing that but facing many issues.

1. I have an iframe inside each slide, If I use index as the :key then all the iframe url gets messed up. For example the removed slide iframe url gets added to next one.
2. If I use a unique id as :key, it refreshes iframe as well as the vueper slider does auto slide to last page for some reason.

Please note I have multiple items per page and is using template slot content.

Please let me know.

Thanks

**Comment by antoniandre** [comment]
Hi @abhijithbabu,

Sorry for the late reply!
Can you provide me with your code so I can help you? Ideally a Codepen reproduction.
Cheers.

**Comment by antoniandre** [comment]
Closing issue do to inactivity. Please reopen if not solved.
