### ISSUE TITLE
option to enable/disable looping

### ISSUE THREAD

**Issue by andrewharvey** [antoniandre/vueper-slides#123]
Nice to have an option to enable/disable looping from one end to the other

**Comment by andrewharvey** [comment]
working on this at https://github.com/andrewharvey/vueper-slides/tree/wrap

**Comment by antoniandre** [comment]
Hi @andrewharvey,

Thanks for your suggestion, not sure I understand though, is that what you are looking for?
https://antoniandre.github.io/vueper-slides/#ex--add-remove-slides--disable

In this example, with the option `:infinite="false"` (and you can disable the arrows on edges with `disable-arrows-on-edges`), the infinite mode (= looping) is disabled.

https://antoniandre.github.io/vueper-slides/#ex--add-remove-slides--disable

Let me know if that helps!
Cheers.

**Comment by andrewharvey** [comment]
When I try that example then it's working as expected it won't loop back to the other end, however when I implemented that :infinite="false" in my app, if you swipe right at the start it would scroll all the way to the last item. Not sure why :shrug:, it only stopped doing that once I made that patch in my fork.

I'll close this then unless I can put together a repro.

**Comment by andrewharvey** [comment]
> When I try that example then it's working as expected it won't loop back to the other end, however when I implemented that :infinite="false" in my app, if you swipe right at the start it would scroll all the way to the last item. Not sure why ￼, it only stopped doing that once I made that patch in my fork.

I haven't thoroughly tested, but seems like I needed to set `disable-arrows-on-edge` for it to work as expected.
