### ISSUE TITLE
prop "video" missing from video's example in documentation

### ISSUE THREAD

**Issue by D3m1urg0** [antoniandre/vueper-slides#124]
I just loaded the video example in my own project but cant get the video loading.

i did a reproduction of the issue in Codesandbox

https://codesandbox.io/s/vueperslide-video-test-0kqzu

it simply loads images and contents but none of the video slides (inner and iframe) will load a video

**Comment by D3m1urg0** [comment]
I found that it's just needed to add the prop "video" to the vueper-slide.

I suggest to fix the docs and the examples :)

**Comment by antoniandre** [comment]
Hi @D3m1urg0,

Thank you very much for your feedback and reporting the mismatch in the documentation.
Now fixed: https://antoniandre.github.io/vueper-slides/#ex--videos!
