### ISSUE TITLE
Open slide link in new tab

### ISSUE THREAD

**Issue by antoci-alin** [antoniandre/vueper-slides#125]
Hello there! 

One of the features that I would love to be there is opening slide links in a new tab. Currently, it's a basic a:href item, but there should be also an option to open the links in a new tab.

Thanks!

**Comment by antoniandre** [comment]
Hi @antoci-alin,

Thanks for your suggestion. This is now an option in Vueper Slides 2.13.0.
https://antoniandre.github.io/vueper-slides/#ex--link-on-the-whole-slide

Hope it helps!

Please reopen if not solved. :)

**Comment by antoci-alin** [comment]
Just in time for production release 😂. Thank you so much!
