### ISSUE TITLE
vuper slider video Issue

### ISSUE THREAD

**Issue by hendawee** [antoniandre/vueper-slides#127]
when using video with autoplay the slide swipe before the video ended

**Comment by hendawee** [comment]
any one can fix this issue  ??
when content is video and slider property autoplay true 
the slider not swipe until video ended

**Comment by antoniandre** [comment]
Hi @hendawee, 
This is not a very helpful issue report: please share your code and elaborate. 
Also check in the documentation here in case you missed something: https://antoniandre.github.io/vueper-slides/#ex--videos: you can swipe while the video is autoplaying.

**Comment by hendawee** [comment]
Hi
I do not want Swipe while video is autoplay ...i want stop swipe while
video is playing and autoplay is true
Waiting your reply

**Comment by hendawee** [comment]
why slider don't stop swipe when video is playing , it should stop swiping when the content is video and user play it to the end of video and at the end of video resume swipe

**Comment by antoniandre** [comment]
Please learn the respect and only reopen when you understand that some people work for free for other people.
Come back with a codepen example or pick another library.
