### ISSUE TITLE
"Cannot read property 'install' of undefined"

### ISSUE THREAD

**Issue by chillikid** [antoniandre/vueper-slides#128]
I'm trying to get Vueper Slides working in my Nuxt app, and have installed it as a plugin. 

This is my vueperslides.js file in the plugin folder:

`import VueperSlides from 'vueperslides'
import VueperSlide from 'vueperslides'

import 'vueperslides/dist/vueperslides.css'

Vue.use(VueperSlides, VueperSlide)`

Then in Nuxt Config 

`plugins: ['~/plugins/vue-horizontal.js', '~/plugins/vueperslides.js'],`

When I compile though this is the error I am seeing. 

![image](https://user-images.githubusercontent.com/14308622/109505517-93e5ee00-7a94-11eb-9149-77dc5bc01b56.png)

I'm pretty much a novice, and have no idea how to fix this problem, or really what the error means.

**Comment by antoniandre** [comment]
Hi @chillikid,

The simplest is to import Vueperslides only in the component where you need it:

```js
import { VueperSlides, VueperSlide } from 'vueperslides'
import 'vueperslides/dist/vueperslides.css'

export default {
  components: { Swiper, SwiperSlide, VueperSlides, VueperSlide },
  ...
```

This way, you don't need a plugin and don't need to declare it in nuxt.config.js, and you also lazy-load the Vueper Slides library to only the view that requires it, when the user visits that page.

Hope it helps, please reopen if not solved. :)
