### ISSUE TITLE
Support server side rendering

### ISSUE THREAD

**Issue by antoniandre** [antoniandre/vueper-slides#13]
In regards to issue https://github.com/antoniandre/vueper-slides/issues/10, the request is to support server side rendering.

**Please note that in Nuxt you can use Vueper Slides by wrapping your slideshow with the `<no-ssr>` tag. (refer to issue https://github.com/antoniandre/vueper-slides/issues/6)**

**Comment by antoniandre** [comment]
`Document` and `window` are part of DOM so it will not be compatible with SSR as long as DOM is not accessible from there.
Putting checks around those variables will not help build the slideshow from server side if DOM is not available.
I will do some tests to see if I can split what can be done from SSR and what can't and will decide if the code refactoring and code complexity increase is worth it.

I will close this issue when I have done the tests or modifications.

**Comment by AndrewBogdanovTSS** [comment]
@antoniandre could you describe what exactly is dependent on Window and Document? Do you generate your markup using document methods? If you use vue templates with directives such as v-for - it will work fine with SSR as well as using render function generative nature

**Comment by antoniandre** [comment]
Hi @AndrewBogdanovTSS, Thanks for your feedback and sorry for the delay I am very busy at the moment.
I haven't spent much time on Nuxt but it seemed logic to me that trying to render the slideshow without DOM is not possible.
What I need when vueperslides is mounted in DOM is: adding event listeners in `document`, checking if the device has a touchscreen from `window` and appending slide clones in `document` in DOM when infinite mode is on.
That's about it. If you can find a way to get it working without DOM, I am happy to modify the code.

**Comment by TheNoim** [comment]
> What I need when vueperslides is mounted in DOM is: adding event listeners in document, checking if the device has a touchscreen from window and appending slide clones in document in DOM when infinite mode is on.

This is nothing you need to do. SSR is about rendering the skeleton and not about adding the logic. By just skimming over how a slider works, you could render the basic structure and add everything other in the browser later. For a static slide you don't need the dom at all.

**Comment by AndrewBogdanovTSS** [comment]
@TheNoim is right, you just need to render DOM that is related to slides and add functionality that is dependant on `window` and `document` only once those are available, for example in `mounted` hook

**Comment by antoniandre** [comment]
Quick heads up! 
SSR is now supported in Vueper Slides since version 1.20.3.
Now Vueper Slides v2 is released and tested on Nuxt 2: #55.

**Comment by AndrewBogdanovTSS** [comment]
@antoniandre should this one also be closed? #50
