### ISSUE TITLE
TypeError: _vm.$refs.vueperslides2.goToSlide is not a function

### ISSUE THREAD

**Issue by SionaFernandes** [antoniandre/vueper-slides#133]
When Using the Thumbnail Gallery when the thumbnail is clicked, it does not work. 
The example code works as well as codepen. 
The project throws this error .

![Screenshot 2021-03-10 at 2 01 52 PM](https://user-images.githubusercontent.com/51289294/110599757-35fa8a00-81a9-11eb-99ff-33be0b4354f8.png)

What can be done to fix this error ? 
Thanks in advance

**Comment by antoniandre** [comment]
Hi @SionaFernandes,
Please look at this example where the goToSlide function is available with (I guess?) the same code: https://codepen.io/antoniandre/pen/ZEGEydP

You may have an issue in your code, maybe a missing `ref="vueperslides2"`? Or maybe trying to access this function before mounted? If so, just make sure in your template that you check the existence of $refs.vueperslides2 before you call a function from it. Just like in the Codepen: `@slide="$refs.vueperslides2 && $refs.vueperslides2.goToSlide($event.currentSlide.index, { emit: false })"`. In this way, there won't be any issue when the Vueperslides componenent is not yet ready, and as soon as it will be ready, the function will be available by a Vue internal variables update that rerenders the DOM.

I hope it helps, please reopen with a fork of the Codepen if not solved! :)
