### ISSUE TITLE
conf not initialised

### ISSUE THREAD

**Issue by flxsource** [antoniandre/vueper-slides#136]
I've got a pretty basic component, as below.

```
<template>
    <vueper-slides autoplay>
        <vueper-slide v-for="(slide, i) in slides" :key="i" :title="slide.title" :content="slide.content" />
    </vueper-slides>
</template>

<script>

import 'vueperslides/dist/vueperslides.css';
import { VueperSlides, VueperSlide } from 'vueperslides';

export default {
    components: {
        VueperSlides,
        VueperSlide,
    },

    data: () => ({
        slides: [
            {
                title: 'Slide #1',
                content: 'Slide content.'
            },
            {
                title: 'Slide #2',
                content: 'Slide content.'
            },
            {
                title: 'Slide #3',
                content: 'Slide content.'
            },
            {
                title: 'Slide #4',
                content: 'Slide content.'
            },
        ]
    }),
}

</script>
```

However, I'm getting the following error:
```
Uncaught TypeError: Cannot read property 'slideRatio' of undefined
```

It appears the `conf` computed property is undefined - the same as all the other computed properties. The data object is fine. Am I missing some initialisation step here?

**Comment by antoniandre** [comment]
Hi @flxsource,

Sorry for the late reply.
Your code looks completely fine and should be working, as per this demo where I copied your code: https://codepen.io/antoniandre/pen/jOydQbP?editors=1010

There could be a mixup in your environment config, could you try to update Vue and Vueper Slides?

Hope it helps. 
If not solved, please reopen with the version of Vue and Vueper Slides that you are using, whether you use it in Nuxt, and ideally provide a fork of the Codepen where you reproduce the issue if you can.

Cheers! :)
