### ISSUE TITLE
div of vueperslide__loader is empty!

### ISSUE THREAD

**Issue by nekooee** [antoniandre/vueper-slides#139]
Hi, I used "lazy lazy-load-on-drag", but browser only show white screen before load. I checked and realized that inside ofvueperslide__loader is empty. 
my code is:
```
<template>
    <vueper-slides fade :rtl="rtl" fractions progress lazy lazy-load-on-drag
                   :fixed-height="height + 'px'">
        <vueper-slide v-for="(slide, i) in slides" class="focus:outline-none"
                      :image="slide.image" :key="slide.id"
        />
        <template v-slot:loader>
            <i class="mdi mdi-loading text-2xl text-orange"></i>
            <span>Loading...</span>
        </template>
    </vueper-slides>
</template>
```

and result :
![image](https://user-images.githubusercontent.com/6003803/113488504-d6f01280-94d3-11eb-988a-db0de457e48a.png)

can you help me?

**Comment by antoniandre** [comment]
Hi @nekooee,
Sorry for the delay.
You probably have to update Vue, here is a working example for you: https://codepen.io/antoniandre/pen/LYxqzyW?editors=1010

Hope it helps. Please reopen if not solved :)

**Comment by nekooee** [comment]
> Hi @nekooee,
> Sorry for the delay.
> You probably have to update Vue, here is a working example for you: https://codepen.io/antoniandre/pen/LYxqzyW?editors=1010
> 
> Hope it helps. Please reopen if not solved :)

thank you. my view version is 2.1.7. this feature doesn't work with view 2?
