### ISSUE TITLE
Improve swipe performance on Android

### ISSUE THREAD

**Issue by matejmachac** [antoniandre/vueper-slides#14]
Hi again.
food for thought: Have you considered switching to 3d transforms, or using will-change: transform on the track for improving swipe performance? CSS transitions should be pretty performant themselves, but there is something about that swipe animation, that causes lag on Android devices (chrome 53). Compared to how iOS handles the animation, its night and day. I would just like to know your view on that. Thanks.

**Comment by antoniandre** [comment]
Hi @matejmachac,
I suggest that I modify the CSS transformations on a branch and let you try as I don't have any android device. If there is any benefit I will merge into master. 👍

**Comment by antoniandre** [comment]
Hi @matejmachac,

I released version 1.13.4 including the transform changes under the npm tag `issue-14`.
```
npm i --save-dev vueperslides@issue-14
```

- replaced translateX, translateY with translate3d
- added will-change property while dragging

Please test and let me know if you see an improvement.
Could you also have a look on the parallax feature on Android for me please? 
to check if the translation is smooth as you scroll - I replaced the `translateY` with `translate3d` in that one.

**Comment by antoniandre** [comment]
Hi @matejmachac, did it solve your issue?

**Comment by antoniandre** [comment]
Considering `translate3d` as an improvement of 2d translations, I decided to merge this branch into master.
