### ISSUE TITLE
Autoplay running well but gives "Error : Cannot read property 'duration' of undefined" after reloading the page

### ISSUE THREAD

**Issue by zayyanerdiansyah** [antoniandre/vueper-slides#155]
Hi, I am newbie in Vue 3 and using vueper slides for my carousel. Thank you for your great package.
I develop an autoplay images carousel in a website, but sometimes it's running well and sometimes I found this error in my code:
![image](https://user-images.githubusercontent.com/79194290/128384416-6249c19a-af94-4c29-92a4-1e1642ff18cb.png)
This is my vue code:
![image](https://user-images.githubusercontent.com/79194290/128384870-d58ce5b3-c3ab-4749-95b6-9e1f2156c4f9.png)
Could you please let me know if you have more information to solve it?

**Comment by diduweiwu** [comment]
> Hi, I am newbie in Vue 3 and using vueper slides for my carousel. Thank you for your great package. I develop an autoplay images carousel in a website, but sometimes it's running well and sometimes I found this error in my code: ![image](https://user-images.githubusercontent.com/79194290/128384416-6249c19a-af94-4c29-92a4-1e1642ff18cb.png) This is my vue code: ![image](https://user-images.githubusercontent.com/79194290/128384870-d58ce5b3-c3ab-4749-95b6-9e1f2156c4f9.png) Could you please let me know if you have more information to solve it?

Yes.I've the same error and autoplay is never available. Anyone could help me out?

**Comment by antoniandre** [comment]
Hi, sorry for late reply.
I don't see any error or warning running the latest Vueper Slides on Vue 3 and Vite. (This is also not observable on the documentation which has the same setup)
Let me know if you still notice some errors. If so please share a reproduction link.
Cheers
