### ISSUE TITLE
Putting bullets above slides possible?

### ISSUE THREAD

**Issue by nkowa** [antoniandre/vueper-slides#158]
Hello, I really enjoy using the vueperslides the slider, however I am trying to have the bullets above the slider instead of below and don't know a way of achieving that, I don't even know if it is possible.
Thank you in advance!

**Comment by antoniandre** [comment]
Hi, sorry for late reply.
This should be done via CSS. 
You can position the class .vueperslides__bullets with `bottom: 100%;` for instance.
That will do: `.vueperslides__bullets {bottom: 100%;}`

Cheers.
