### ISSUE TITLE
change the size of image in responsive

### ISSUE THREAD

**Issue by ludogou** [antoniandre/vueper-slides#161]
Hi ! 
how can i change the size of the images when the slider is displayed on mobile ?

**Comment by antoniandre** [comment]
Hi,
sorry for late reply.
You should just use the `slide-ratio` prop and it will adjust the size automatically to available space, keeping the ratio.
Alternatively, you can set a `fixed-height`, or even put the `slide-image-inside` and style it yourself to apply custom constraints.
Everything is in the documentation with lots of examples.
