### ISSUE TITLE
Styling arrows depending on content size and index

### ISSUE THREAD

**Issue by smarques** [antoniandre/vueper-slides#163]
Hi, I could not find this in the docs, please excuse me if I missed something.
(Vueper is really excellent btw)
I have a slider with

`:visible-slides="4"
      :arrows="true"
      :bullets=false
      slide-multiple`

I'd like to be able to apply different css to the left when we are at the beginning of the slide sequence (first slide in view) and a different css to the right arrow (last slide in view)

This would make it more usable I think, as sometimes you might want to hide arrows when they are somehow 'not necessary'
either because we have a `number of slides < visible_slides` or we are say at the end of the reel and we'd prefer to give more attention to the back arrow and fade away the forward arraow.

Hope I made my point clear.
TIA

**Comment by antoniandre** [comment]
Hi, sorry for late reply.
Maybe you should just use the `disable-arrows-on-edges` prop for that purpose.
If you still need another way, let me know and I will add extra CSS classes.
