### ISSUE TITLE
own arrows icons via the #arrow-left and #arrow-right slots + iconify.

### ISSUE THREAD

**Issue by patriciorivera** [antoniandre/vueper-slides#178]
Awesome Library, thanks.

According [docs](https://antoniandre.github.io/vueper-slides/#ex--arrows-and-bullets)

But using [Iconify](https://iconify.design/) icon framework it idoesnt work.

Stackblitz -> [this](https://stackblitz.com/edit/vitejs-vite-cpppdj?file=src/App.vue)

Sorry if I don't quite understand how to use it.

Regards.

**Comment by antoniandre** [comment]
Hi @patriciorivera,

The arrows slots are working fine and your icons library as well, if you inspect, this is just some CSS to adjust for your case.
The arrows are white by default, and smaller. 

<img width="1426" alt="Screen Shot 2022-06-17 at 5 22 29 PM" src="https://user-images.githubusercontent.com/22971289/174408461-7d25b63b-03a8-4cf7-b8ec-8c4f63ef7956.png">

Just removing some padding, and adding a background to the slide, you can already see the SVG icon:

<img width="1432" alt="Screen Shot 2022-06-17 at 5 23 38 PM" src="https://user-images.githubusercontent.com/22971289/174408468-0d9544a1-d6b8-4369-80ae-2822b83bcbfb.png">

Cheers.
