### ISSUE TITLE
Disable right arrow keyboard event(or both right and left) without disabling whole vueper-slides component via disabled prop

### ISSUE THREAD

**Issue by aleksandarcrvc** [antoniandre/vueper-slides#180]
I have specific case where in application we need to disable next button based on app state and that is possible by using external arrow keys and visibility logic. The problem is even if I disable next button there is still possibility for user to goes further and slide content with keyboard right arrow key. I can use disable prop on vueper-slides level but then previous button is disabled as well and user is not able to go back. I read documentation and also goes trough source code but didn't find proper way to implement this case scenario

**Comment by antoniandre** [comment]
Hi @aleksandarcrvc, 
In this case you should remove the slides you don't want to be accessible from your array.
Something like:

```vue
    <vueper-slide
      v-for="(slide, i) in filteredSlides"
      :key="i"
      :image="slide.image"
      :title="slide.title"
      :content="slide.content">
    </vueper-slide>
```

with slides being your original full array of slides, and filteredSlides a computed that filters out the slides you don't want to show up.

Hope it helps. please reopen if not solved. :)
