### ISSUE TITLE
Deactivate entire slide functionality via API / breakpoint

### ISSUE THREAD

**Issue by LucPestille** [antoniandre/vueper-slides#22]
The use case I have for carousels most of the time is for mobile / tablet only, and displaying the full content at higher breakpoints, completely removing the carousel at that point.

It would be very useful to have a breakpoint event to do this - unwrap / remove _all_ the markup / events and just leave the slides' content on the page to be styled as needed at that breakpoint.

As far as I can see, this isn't possible in the current version?

I could just duplicate and hide / show the carousel / content, but that's not DRY by any means...

**Comment by antoniandre** [comment]
Hi @LucPestille,

This is how you can do it using a single slider, no duplicate, with a bit of CSS. 
https://codepen.io/antoniandre/pen/rbzyOE?editors=1100
Hope it helps.
