### ISSUE TITLE
Static title/content while slides change in background

### ISSUE THREAD

**Issue by dapperdanman1400** [antoniandre/vueper-slides#24]
It would be nice to be able to have text that doesn't change in the title/content while the background slides do change. Right now the best I can do is make duplicate titles/content in all my slides, but that's nowhere near ideal.

**Comment by antoniandre** [comment]
Hi @dapperdanman1400, Thanks for your feedback.

I understand what you mean, but this is not something that should be done inside the library.
You can achieve this by placing the slide content outside of vueperslides and positioning absolute.
In this context, there is no reason to place the content inside a slide if it's going to be the same on all the slides.
