### ISSUE TITLE
Use a link on the entire slide

### ISSUE THREAD

**Issue by ahmedfaical** [antoniandre/vueper-slides#27]
Hello, I tried to use a link or a route name in the entire slide but without success
below my try
```
<vueper-slides autoplay fade slide-content-outside="top" :slide-ratio="0.3">
     <vueper-slide
	   v-for="(slide, i) in slides"
           :key="i"
	   :image="slide.image">
           <a :href="slite.route" slot="slideContent"></a>
    </vueper-slide>
</vueper-slides>

        slides: [
        {
		image: "/banners/banner1.jpg",
                 route: "link-to-page-1"
        },
        {
		image: "/banners/banner2.jpg",
                 route: "link-to-page-2"
        }
      ],
```

**Comment by Redani** [comment]
Hi, I'm interested too to know how to achieve that, I was pretty surprise when I found out it wasn't documented... :S

**Comment by antoniandre** [comment]
Hi @ahmedfaical, @Redani, 
Thanks for your feedback, you pointed out a missing feature!
It is now possible to do so from version 1.17.0.
Please refer to this example: https://antoniandre.github.io/vueper-slides/#ex--link-on-the-whole-slide

Hope it helps.
