### ISSUE TITLE
Multiple items at once

### ISSUE THREAD

**Issue by lbineau** [antoniandre/vueper-slides#3]
Hi @antoniandre,

Your slider/carousel looks promising.
Do you plan to support multiple items? (like on slick http://kenwheeler.github.io/slick/)

Thank you.

**Comment by antoniandre** [comment]
Hi @lbineau,
Thanks for your interest.
Yes it is on the list of features to come next. I will close this Issue when implemented.

**Comment by lbineau** [comment]
I'm happy to know it is on you todo list. Thanks for the update.

**Comment by matejmachac** [comment]
+1. @antoniandre  I see you already started working on it. Nice job!

**Comment by antoniandre** [comment]
Hi I am happy to announce this fairly big chunk is out.

Now available in version 1.13.0.

Please refer to https://antoniandre.github.io/vueper-slides/#ex--show-multiple-slides
