### ISSUE TITLE
Link on the on the entire slide + touchable

### ISSUE THREAD

**Issue by chou666** [antoniandre/vueper-slides#32]
Related to #27, when vueper-slides is touchable, the drag and drop produce click event and follow the link. Is it possible to prevent click event if drag started ?

`<vueper-slides>
 <vueper-slide link="/" ></vueper-slide>
</vueper-slides>`

**Comment by antoniandre** [comment]
Hi @chou666,
You're right, that should be possible.
It is now fixed in version 1.19.0, please refer to the updated example: https://antoniandre.github.io/vueper-slides/#ex--link-on-the-whole-slide

Hope it helps.

**Comment by chou666** [comment]
Thanks a lot for your job ! issue fixed !
