### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by parkhm0829** [antoniandre/vueper-slides#34]
[Vue warn]: Invalid prop: type check failed for prop "initSlide". Expected , got Number.

found in

---> <VueperSlides>
       <MainPhishingPage> at D:\Project\Datauniverse\2019\antiscam\partner.antiscam.co.kr\src\components\web2.vue
         <Root>

[Vue warn]: Invalid prop: type check failed for prop "slideRatio". Expected , got Number.

found in

---> <VueperSlides>
       <MainPhishingPage> at D:\Project\Datauniverse\2019\antiscam\partner.antiscam.co.kr\src\components\web2.vue
         <Root>

[Vue warn]: Invalid prop: type check failed for prop "speed". Expected , String, got Number.

found in

---> <VueperSlides>
       <MainPhishingPage> at D:\Project\Datauniverse\2019\antiscam\partner.antiscam.co.kr\src\components\web2.vue
         <Root>
[Vue warn]: Invalid prop: type check failed for prop "transitionSpeed". Expected , String, got Number.
[Vue warn]: Invalid prop: type check failed for prop "initSlide". Expected , got Number.
......

occured in IE11

how can I solve these problems

**Comment by antoniandre** [comment]
Hi @parkhm0829, Sorry for the delay.
have you tried the documentation page on IE 11 to see if it breaks too? 
I haven't seen an error on my end.

If this is not solved, can you show you code?

**Comment by antoniandre** [comment]
Closed for inactivity.
