### ISSUE TITLE
Feature Request: Specify spacing and display whatever fits

### ISSUE THREAD

**Issue by killroyboy** [antoniandre/vueper-slides#36]
Rather than indicating the number of items I would like to display, I would like to specify the spacing between and then render as many as will fit within the provided space and cut off (or fade away) any overflowing content.

The approach makes things simpler with responsive design.

Is this already possible? And I'm missing it?

**Comment by antoniandre** [comment]
Hi @killroyboy, 
This is not possible and what you are looking for is just inline images in a div that has a nowrap with a scrollbar.

You don't need this slideshow to do this, just few lines of CSS.
