### ISSUE TITLE
is there a way to add html element?

### ISSUE THREAD

**Issue by Zed-FED** [antoniandre/vueper-slides#39]
I am building a Testimonial.
i want different client images for different testimonial. i want something like that but that 's not working for me. i just want to add custom html elements.
is there a proper way to achieve this?

```
<vueper-slides autoplay :bullets="false" class="no-shadow">
      <vueper-slide v-for="items in slides" :key="items.id" :title="items.title" :content="items.content">
        <img :src="`images/${items.clientImage}`" alt=""/>
      </vueper-slide>
    </vueper-slides>
```

**Comment by antoniandre** [comment]
Hi @Zed-FED,
Yes this is possible and you can refer to this example: https://antoniandre.github.io/vueper-slides/#ex--complex-slide-title-and-content

What you are missing from this example of the documentation is:

> if both :title="Some title" and slot="slideTitle" are provided, only the title from the attribute will be displayed.
> if both :content="Some content" and slot="slideContent" are provided, only the content from the attribute will be displayed.

So make sure to remove the title and content attributes if you provide them through slots.
Let me know if you need more help.

**Comment by Zed-FED** [comment]
@antoniandre Thanks for the solution. it works for me. :)
