### ISSUE TITLE
Make vue a peerDependency

### ISSUE THREAD

**Issue by antony** [antoniandre/vueper-slides#4]
Current version breaks nuxt because it forces the vue dependency to .16 when nuxt uses .17

Package shouldn't include Vue by itself, because the hosting application will provide it.

**Comment by antoniandre** [comment]
Hi Antony, you are right, I haven't noticed this. Vue will be removed from the dependencies in the next version.

**Comment by antoniandre** [comment]
fixed in Version 1.11.2.
Vue doesn't have to be a peer dependency, placing it in dev dependencies will fix the issue. 
Vue was embedded in vueperslides because it was listed as a dependency and not dev dependency.
