### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by ahmedfaical** [antoniandre/vueper-slides#41]
Hello,
When i generate report in lighthouse i get this report : Does not use passive listeners to improve scrolling performance (Consider marking your touch and wheel event listeners as passive to improve your page's scroll performance.)
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners?utm_source=lighthouse&utm_medium=extension
And i found that the problem comes from this file :
<img width="416" alt="Screenshot 2019-07-19 at 16 14 51" src="https://user-images.githubusercontent.com/25527820/61549698-a7238180-aa48-11e9-8ae8-bd7c84378be1.png">
I think it will be awesome if you can add {passive : true} for touch and wheel listeners as bellow :

<img width="1117" alt="Screenshot 2019-07-19 at 16 15 08" src="https://user-images.githubusercontent.com/25527820/61549803-ddf99780-aa48-11e9-80f9-d3d8777d2208.png">

**Comment by antoniandre** [comment]
Hi @ahmedfaical, Thanks for your feedback. This should be good in Version 1.20.0.
I also combined a feature request in #33 to add an option to prevent vertical scrolling while dragging, so it looks more like that:
![image](https://user-images.githubusercontent.com/22971289/61576834-220c9b00-ab22-11e9-9cf2-b9da45a945ff.png)

Should not matter if you don't disable vertical scroll.
Hope it helps!

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if not solved.
