### ISSUE TITLE
$slots not defined error

### ISSUE THREAD

**Issue by demiro** [antoniandre/vueper-slides#44]
I am getting this error:

> [Vue warn]: Error in mounted hook: "TypeError: Cannot read property '$slots' of undefined"

when using like this:

```
    <vueper-slides v-if="photos" fixed-height="100vh" :arrows="false" :bullets="false" :autoplay="true" :transitionSpeed="800"
        :speed="8000" :touchable="false">
        <vueper-slide v-for="photo in photos" :image="photo.url"></vueper-slide>

    </vueper-slides>
```

**Comment by antoniandre** [comment]
Hi @demiro, This happened when slideshow had no slides. I've pushed a fix, let me know if that solves the issue.

**Comment by olineup** [comment]
Hi @antoniandre . Im using 1.20.3 and have same error.
![image](https://user-images.githubusercontent.com/55979412/66839455-1b4dc280-ef6f-11e9-863b-ef0e34d376f8.png)

**Comment by antoniandre** [comment]
Hi @olineup, sorry I missed your comment, if not solved yet can you share your code please?

**Comment by jonalxh** [comment]
It happens to me in 2.8.3 version, I have dynamic slides and there are moments when there is not data to show. How to prevent the error?
