### ISSUE TITLE
filter on props

### ISSUE THREAD

**Issue by lazynewt** [antoniandre/vueper-slides#46]
Is there any way currently to use moment or another filter for props e.g :content="myValue | moment('Do-MMM-YYYY HH:mm:ss')"

**Comment by antoniandre** [comment]
Hi @lazynewt,
This should be possible and independent of `vueper-slides`.
I suspect that your moment filter returns a moment object and not a string.

Do you have an error in the end? 
Please provide your code, errors and ideally reproduction link if you still have the error.

**Comment by antoniandre** [comment]
Closed for inactivity. Please reopen if not solved.
