### ISSUE TITLE
Minimal css

### ISSUE THREAD

**Issue by antony** [antoniandre/vueper-slides#5]
Hi,

It states in the docs that the default css is barebones / minimal css. It's quite barebones, but it has this near impossible to-track down box-shadow:

```
-webkit-box-shadow:0 0 20px rgba(0,0,0,.25);box-shadow:0 0 20px rgba(0,0,0,.25);
```

on the before and after pseudo-elements of the parallax wrapper, which requires a fair bit of css jiggery-pokery to get rid of.

More of a recommendation, but none of my designs have that, so I always have to remove it using css overrides. It would be great if it was an optional "enhancement" rather than a default :)

**Comment by antoniandre** [comment]
@antony, I understand you may not want the `box-shadow`.
As mentioned in https://antoniandre.github.io/vueper-slides/#external-css, it is not embedded directly in the library but already placed in an external css file. 
This file is the default styles and not the bare minimum. 

You can override these rules, as you already did, or don't include the file at all if you want the bare minimum styles.
(You may want to refer to the scss file itself to see unminified version: https://github.com/antoniandre/vueper-slides/blob/master/src/components/styles.scss)

As this file is here for cosmetic purpose, the box shadow is where it should be and part of the default style I want to give to Vueper Slides.

**however, what I can do, is add a `no-shadow` class that you can set on `<vueperslides>` tag. This will prevent the shadow.**

**This is available from version 1.12.0. Refer to https://antoniandre.github.io/vueper-slides/#external-css.**
