### ISSUE TITLE
Cannot set property 'render' of undefined in Nuxt.js

### ISSUE THREAD

**Issue by leandrocodes** [antoniandre/vueper-slides#50]
I had put my import as a plugin:

```
import Vue from 'vue'
import { VueperSlides, VueperSlide } from 'vueperslides'
import 'vueperslides/dist/vueperslides.css'

Vue.use(VueperSlides)
Vue.use(VueperSlide)
```

And getting it at nuxt.config.js
` `plugins: ['~/plugins/vueper']`,`

Trying to render like this:
````
    <no-ssr>
      <vueper-slides class="no-shadow" :visible-slides="3" :slide-ratio="1/4" :dragging-distance="70">
        <vueper-slide v-for="i in 9" :key="i" :title="i.toString()"></vueper-slide>
      </vueper-slides>
    </no-ssr>

What else i supposed to do? 🤔

**Comment by antoniandre** [comment]
Hi @leandrocodes, sorry for late reply.
I have given a try in Nuxt 2 with Vueper Slides 2, I wrote the detailed steps here: https://github.com/antoniandre/vueper-slides/issues/55#issuecomment-557780838.

If you want to use a plugin that's fine, your plugin should be named `vueper.js` I guess according to `~/plugins/vueper`.

Next thing, you should remove the no-ssr tag.
If it still does not work, please retry with Vueper Slides 2 and Nuxt 2.

Hope it helps, let me know.

**Comment by leandrocodes** [comment]
Ok, thanks for the help!
