### ISSUE TITLE
responsive images 

### ISSUE THREAD

**Issue by navinSing** [antoniandre/vueper-slides#51]
I struggled hard .. and spent almost more than 10 hours with no solution. Tryying to avoid the cut in the image, if the web page is resized the image gets trimmed. I tried all fixed-height, parallax.

But get an example to avoid the cut in the image. I am ok to have empty content/ transparent content behind the slide if image is small.

**Comment by antoniandre** [comment]
Hi @navinSing,
I struggled hard too developing this lib for others, more than 10 hours. Think about it.

But if you want help you should at least share your code and a reproduction link so that I know what you are talking about.
