### ISSUE TITLE
Multiple slides behavior

### ISSUE THREAD

**Issue by Byloor** [antoniandre/vueper-slides#58]
I am extensively using vueper slides for my project. I am very glad to see the multiple slides option. 
The behavior I want to achieve is slide till the end of the complete show. . i,.e, if visible slides are 3, and total slides are 9, then slide function should work until the last slide is at the first positon. I want to know if this is achievable.  

`            <vueper-slides class="no-shadow" :arrows-outside="false" :visible-slides="3" :slide-ratio="1/ 4" :dragging-distance="70" @before-slide="logEvents"  @ready="logEvents" :bullets="false" slide-content-outside="bottom">
 <vueper-slide v-for="(slide, index) in model.images" :key="index" :image="slide.image">
                    <div slot="slideContent">
                        <v-layout style=" text-align: left; margin-left: 2%;width: 33.33%;">
                            <div> Description ....</div>                  
                        </v-layout>
                    </div>
                </vueper-slide>
            </vueper-slides>`

and is there a possiblity to choose which among the 3 visible slides is the current Slide. This would make it possible for currentSlide to always be on the left end.

**Comment by antoniandre** [comment]
Hi @Byloor, 
It looks like you want to do something like that: 
https://github.com/antoniandre/vueper-slides/issues/56

**Comment by Byloor** [comment]
@antoniandre : similar but not exactly. I wanted the active slide always to be at the right, or atleast to have an option of position of active slide. without too much of css. But thanks for the link , I went for the solution in #56

**Comment by antoniandre** [comment]
Ok closing the issue then. 

> I wanted the active slide always to be at the right
Having the current slide always on the right is not common, I think this should be done in css, btw there is a css class for the active slide.
