### ISSUE TITLE
the new version probably broke my front

### ISSUE THREAD

**Issue by rafasluize** [antoniandre/vueper-slides#60]
Hello. I was using vueper cdn and in recent days I see some strange behaviors, since my site was already in production and always worked. can you help me?

the cdn link I'm using is this: https://unpkg.com/vueperslides?ver=5.0.7

**Comment by rafasluize** [comment]
I need you to make me available the old version :(

**Comment by rafasluize** [comment]
I noticed that the biggest problem was changing the slideContent slot to content and the slideTitle slot that was removed. And some things about arrows.
I tried to change these details based on the new doc, but it didn't solve

**Comment by antoniandre** [comment]
Hi @rafasluize, Vueperslides has changed a lot and a major release (here v2) will require to modify your code accordingly.
Either share your code so we can see what is wrong, or use an older version from the CDN, this is how: `https://unpkg.com/vueperslides@1.21` for instance.
