### ISSUE TITLE
Allow syncing 2 slideshows

### ISSUE THREAD

**Issue by zhuxiaoyu88** [antoniandre/vueper-slides#63]
Please add feature for grouping, so other slider can control the first slider

**Comment by antoniandre** [comment]
Hi @zhuxiaoyu88, thanks for this idea, I'll be adding support for this soon.
Will let you know when ready.

**Comment by antoniandre** [comment]
Hi @zhuxiaoyu88,

This is now possible in version 2.2.0.
Documentation: https://antoniandre.github.io/vueper-slides/#ex--synced-instances
Demo: https://codepen.io/antoniandre/pen/jOEWPjz?editors=1100

**Comment by zhuxiaoyu88** [comment]
Thank you I'll try it ! @antoniandre
