### ISSUE TITLE
[Feature Request] Offset slider

### ISSUE THREAD

**Issue by JakuninOleg** [antoniandre/vueper-slides#64]
My request is to add ability to offset slider, so you start with first slider i.e. 200px to the right, but the slider itself is full width.
In Vue-Awesome-Swiper it's called Centered Slides.

You may observe the idea here
https://www.raiffeisen.ru/ (cards under the calculator)

**Comment by antoniandre** [comment]
Hi @JakuninOleg,
Is this what you are looking for? https://github.com/antoniandre/vueper-slides/issues/56#issuecomment-553680405

I will have a closer look soon to see if I can facilitate the work done in #56 with an option in Vueper Slides.

**Comment by JakuninOleg** [comment]
Yeah, it's kinda what I'm looking for, but my the slidet doesn't work with this code now, maybe I don't get the documentation right

`<template>
  <vueper-slides
    :class="{ offsetslidefirst: slides[0], offsetslidelast: slides[-1] }"
    @before-slide="beforeSlide"
    :visible-slides="3"
    :slide-ratio="1/4"
    :dragging-distance="35"
    class="no-shadow"
    :show-multiple-slides="true"
  >
    <vueper-slide
      v-for="(slide, index) in slides"
      :key="index"
      :title="slide"
      :style="'background-color: ' + ['#ff5252', '#42b983'][slide % 2]"
    />
  </vueper-slides>
</template>

<script>
import { VueperSlides, VueperSlide } from 'vueperslides'
import 'vueperslides/dist/vueperslides.css'

export default {
  components: {
    VueperSlides,
    VueperSlide
  },
  data () {
    return {
      slides: ['1', '2', '3', '4', '5', '6']
    }
  },
  methods: {
    beforeSlide ({ nextSlide }) {
      this.slides[0] = (nextSlide.index === 0)
      this.slides[-1] = (nextSlide.index === this.slides.length - 1)
    }
  }
}
</script>

<style lang="scss">
.offsetslidefirst {
  .vueperslides__track-inner {
    transform: translate3d(33.333%, 0px, 0px) !important;
  }
}

.offsetslidelast {
  .vueperslides__track-inner {
    transform: translate3d(-99%, 0px, 0px) !important;
  }
}
</style>
`

**Comment by antoniandre** [comment]
Hi @JakuninOleg,

I have created a Codepen to reproduce a working behavior:
https://codepen.io/antoniandre/pen/mdyVoEr

Please have a look and let me know if you have a problem.

**Comment by JakuninOleg** [comment]
@antoniandre Good day!

Yeah, it works, thanks!
Additional option would be great, cause I need to use calc in css I guess to make it truly adaptive.

Also, did you think about gap option between slides? Really like this plugin, looking forward using it in production ;) 

Another feature - attaching prevslide and nextslide methods to different elements outside the vueperslides component.

**Comment by antoniandre** [comment]
Hi @JakuninOleg, 
Yes I will add this option soon, and gap between slides should also be another option. 

Regarding that one, I did not get it:
> Another feature - attaching prevslide and nextslide methods to different elements outside the vueperslides component.

Are you looking for external controls? https://antoniandre.github.io/vueper-slides/#ex--external-controls

**Comment by JakuninOleg** [comment]
Yeah. missed that point in docs, but that's what I was talking about.

**Comment by antoniandre** [comment]
Hi @JakuninOleg,
Now that you have implemented a working `centered` mode, the main issue is solved (I will still make this an option in a next release).

Regarding the gap feature you were also looking for, this is now available from version 2.3.0.
The `gap` option accept a number in percentage.

https://antoniandre.github.io/vueper-slides/#ex--show-multiple-slides-and-gap

hope it helps.
Closing the issue now.
