### ISSUE TITLE
[Feature Request] Add class to single bullet dynamically.

### ISSUE THREAD

**Issue by TaylorAckley** [antoniandre/vueper-slides#65]
The scenario is a end-user has seen a slideshow previously and the application stores the indexes of the viewed slides and when they return to the slideshow sometime later, add a class to the bullets that have been viewed.

I can use `:style` to add classes to slides based off of state and basically I'm hoping to do the same with a bullet.

If this is possible and I missed something, let me know.

I am also happy to take a stab at this and submit a PR

**Comment by antoniandre** [comment]
Hi @TaylorAckley,
That makes sense, I will work on that soon, will let you know when ready.

**Comment by TaylorAckley** [comment]
Happy to help in whichever way I can.

**Comment by antoniandre** [comment]
Thanks for suggesting help @TaylorAckley! 
I finished the feature already, but I will need to update the documentation as there is a few important things to say about it.
Will ship tonight. ;)

If ever you wanted to contribute in a general way on Vueper Slides let me know via email (you can find my email is in the package.json file) we can discuss the other features to develop!
Cheers.

**Comment by antoniandre** [comment]
Hi @TaylorAckley,
This feature is now available in version 2.4.0.
https://antoniandre.github.io/vueper-slides/#ex--arrows-and-bullets

Hope it helps.

**Comment by TaylorAckley** [comment]
Thanks, I'll give it a try.  I'm sure it's great.   I appreciate you doing that so quickly.

I'll reach out re: contributing.
