### ISSUE TITLE
Bullet point should sync with number of visible slides

### ISSUE THREAD

**Issue by justinliu6165** [antoniandre/vueper-slides#67]
Hello,

I created an illustration to show my issue. At the moment, there are 3 bullet points below my slides but there will only be two sections that you can view: (Slide 1 & Slide 2)  and (Slide 2 & Slide 3). To me, it makes sense to have 2 bullet points there rather than 3.

Is this possible to fix or is there a workaround for this?

<img width="1040" alt="Screen Shot 2019-12-23 at 16 16 29" src="https://user-images.githubusercontent.com/38537698/71368358-a5ce2600-259f-11ea-8b76-83205c155810.png">

Also when the last bullet point is highlighted (Slide 2 & Slide 3 are visible), and i drag to the right (to view Slide 1 and Slide 2), the bullet point moves to the centre but the visible slides bounce back to (Slide 2 & Slide 3). This means i have to drag it twice to show Slide 1.

Thanks again

**Comment by antoniandre** [comment]
Hi @justinliu6165,
I am not sure I understand the issue: the bullet points represent the number of slides in the slideshow. You are supposed to be able to see 3 slides if you have 3 slides in the slideshow, and 3 bullets will show.
3 bullets represent the 3 slide actions to see all the slides.

Counting only the visible slides in the bullets does not let the user know that there are more slides that they could see and therefore is not a good user interface IMO.

There is also the option `slide-multiple` which will create only 2 bullets in your case, representing the 2 slide actions possible to see all the slides. As `slide-multiple` slides all the visible slides at once, you will have 1 and 2 on the slide A and slide 3 on the slide B.


For your second question, I will need your code so I can reproduce to see what's wrong.
Cheers.

**Comment by justinliu6165** [comment]
Hey @antoniandre,
Sorry my explanation may not have been that  clear. But yea, the slide-multiple worked for me. That's what i expected it to work like; to show the number of slide actions that can be taken. That actually removes the other issue as well for me.

Thanks for taking your time to answer me :)
