### ISSUE TITLE
If the length of the slide is 1, there is an error that no screen appears.

### ISSUE THREAD

**Issue by yunseop-kim** [antoniandre/vueper-slides#68]
Hello, Thank you for sharing good open source.
As with the title, there is an error where the screen is blank if the slide is 1

Share the code below.

https://codepen.io/yunseop-kim/pen/MWYvaqM

Thanks again.

**Comment by antoniandre** [comment]
Hi @yunseop-kim,
Thanks for your feedback and for reporting, indeed that's a bug I will push a fix for that soon.

**Comment by antoniandre** [comment]
Fixed in version 2.3.1

**Comment by yunseop-kim** [comment]
@antoniandre Thanks for your fast feedback!
