### ISSUE TITLE
FOUC / Slides piling up on load

### ISSUE THREAD

**Issue by antony** [antoniandre/vueper-slides#7]
I've noticed on first page load, all the slides pile up down the page before suddenly turning into a carousel. Is this the server-side rendered version I'm seeing?

I wonder if there is a way to stop it?

**Comment by antoniandre** [comment]
@antony, this seems to be fairly easy to solve but I can't reproduce.
Can you give me your browser version, reproductions steps and the options you use on your slideshow or a Codepen?
Also the way you include and/or set your CSS is important in case of FOUC, please give more details about it.

**Comment by antony** [comment]
Sure - I'll try to create a codepen for it - in the meantime, you can have a look at https://qa.beyonk.com (top slider) if it helps.

**Comment by antoniandre** [comment]
After looking at your page, it seems that the CSS load for your Vueper Slides is deferred a bit.
So in your environment, you get half-styled content before the Vueper Slides embedded styles are loaded. Unfortunately I cannot accelerate that from the Vueper Slides lib as the CSS at stakes is already in the same file as the rest of the Javascript (SFC .vue file).

So what I suggest you do , is to add this rule to your first-loaded CSS and that should get it sorted:

```css
 .vueperslides:not(.vueperslides--ready) { overflow: hidden; } 
```

This will prevent overflow until Vueper Slides is ready.
(Make sure .vueperslides has a non-static position for the `overflow: hidden` to work)

**Comment by antony** [comment]
Thank you again for your awesome help - I moved the css into the global bundle and fixed the overflow and it seems much better on load now.
