### ISSUE TITLE
image load event

### ISSUE THREAD

**Issue by raykudo** [antoniandre/vueper-slides#70]
```
<vueper-slides
  autoplay
  fixed-height="true"
  :slide-ratio="1/2"
  :arrows="false"
  bullets-outside
>
  <vueper-slide
  v-for="(slide, i) in Images"
  :key="i"
  :image="slide.image_path"
  // wanna get image loading finished event here
  ></vueper-slide>
</vueper-slides>
```

I use vueper-slide as above. I'd like to get image loading finished event like below. Any solutions?

```
<img v-on:load="imgLoadingFinished" />
```

**Comment by antoniandre** [comment]
Hi @raykudo,
This will be available and made easy with the lazy-loading feature that I started few days ago: https://github.com/antoniandre/vueper-slides/compare/lazyloading

Meantime you can still do it manually as you started. Here is a demo for you: 
https://codepen.io/antoniandre/pen/VwYdYRZ

**Comment by raykudo** [comment]
@antoniandre 

Awesome! thanks for the heads up

**Comment by antoniandre** [comment]
Hi @raykudo,
The lazy loading feature is released!  🚀
https://antoniandre.github.io/vueper-slides/#ex--lazyloading
