### ISSUE TITLE
disable-arrows-on-edges not hiding prev arrow on initial load

### ISSUE THREAD

**Issue by brewmanandi** [antoniandre/vueper-slides#73]
version 2.8.2:

On initial load the prev arrow is visible. When I scroll left and right it is gone. Is there some update missing?

**Comment by antoniandre** [comment]
Hi @brewmanandi,
That should be working fine, like in this demo: https://codepen.io/antoniandre/pen/gOpOMOa

If it does not, please share your code so we can investigate.

**Comment by brewmanandi** [comment]
Hi, I prepared a Codepen that shows the issue. It appears when the data array is changes in mounted call:
https://codepen.io/brewmanandi/pen/xxGGywV

**Comment by antoniandre** [comment]
@brewmanandi, 
I see. Thanks for the Codepen that's helpful.
I will have a look to improve that soon.
Will let you know when ready.

**Comment by antoniandre** [comment]
Hi @brewmanandi,
This is now fixed in version 2.8.3 and visible on your Codepen (make sure it's hitting the right version on unpkg.com).
It took some time as I was busy on another project.

Cheers.
