### ISSUE TITLE
Selecting text

### ISSUE THREAD

**Issue by zhuxiaoyu88** [antoniandre/vueper-slides#75]
Is it possible to select text inside vueper content wrapper ? Currently, the text can not be selected or copied. I already replaced the user-select property in class vueperslide__inner but that's not working. Here is my code
`.vueperslides__inner {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}`

**Comment by antoniandre** [comment]
Hi @zhuxiaoyu88,
This is the correct approach, but instead of on `vueperslides__inner ` you should do it on  `.vueperslide__content-wrapper`

**Comment by zhuxiaoyu88** [comment]
Still not working

**Comment by antoniandre** [comment]
Then try `.vueperslide * {user-select: text;}`.

If it does not work, I need your code to help.

**Comment by zhuxiaoyu88** [comment]
Worked, thank you so much !
