### ISSUE TITLE
bullets cannot be hidden with `bullets="false"`

### ISSUE THREAD

**Issue by tony19** [antoniandre/vueper-slides#78]
The docs indicate that the `bullets` Boolean property (`true` by default) sets whether to show/hide the bullets, but setting it to `false` has no effect.

[codepen](https://codepen.io/tony19/pen/WNvgJVd)

**Comment by antoniandre** [comment]
Hi @tony19, 
You actually misplaced the `bullets="false"` it should go on the `vueperslides` tag not the slide itself.

**Comment by tony19** [comment]
Oops. Thanks!
