### ISSUE TITLE
Scaling slider to content

### ISSUE THREAD

**Issue by antony** [antoniandre/vueper-slides#8]
Sorry - hopefully the last question.

Can this carousel scale to fit the content? Our designer has taken issue with the ratio / fixed-height and wants me to fit the slider to the height of the largest content plus some padding.

I can't see an obvious way to do it. Is this something that could be done in CSS, or is there some javascript scaling wizardry I'll run into if I attempt it?

Thanks!

**Comment by antoniandre** [comment]
The slideshow cannot adapt its height from a slide to another (and change height as you slide). This will not be in the next features. Possibly later.

But what you seem to want is to have the greatest height image as the height of the slideshow and keep ratio when you resize.

if this is what you want, drop the `fixed-height` option and only use `slide-ratio` set with the ratio of your tallest image: let's say the tallest image is 1268x500 then the slide ratio will be 1268/500.
then when you resize, this image will always be the best fit (and the slideshow height will increase decrease accordingly to keep ratio). 

For the other slides that are not as tall, you can choose to let Vueper Slides crop to best fit (with CSS  `backround-size`) or you can combine with the option `image-inside` and style as you wish with some CSS.

Also according to what you want you may be interested to look at the different values of the CSS property background-size, using `contain` may suit you, check the difference with `cover` or a percentage value, it will have totally different results.

**Comment by antony** [comment]
@antoniandre I've been asked to make the slideshow height match the longest *text* height with a bit of padding. I think the slide ratio could be really useful for this - I hadn't realised that you can set it so exactly!

I'll give it a go and report back.

**Comment by antoniandre** [comment]
Please try previously mentioned solution and close issue if it is not a Vueper Slides issue.
Thanks.

**Comment by antony** [comment]
It didn't really work, because the text wraps as the viewport size changes. It would work well for images, but for text it doesn't really work. I think you'd still need some way of adapting the height of the slideshow dynamically based on the content height.

Not sure if this is something you want to support or not, I'll leave it open for you to decide.

Thanks for your help!

**Comment by antoniandre** [comment]
Vueper Slides won't adapt height to custom content in a near future.
I suggest you use media queries to set height, or define slide content font-size in `view-width`, e.g. `font-size: 1.2vw;`.

you can also define a specific height  in CSS on each slide (e.g. `.vueperslide:nth-child(2)`) or add `padding-bottom`, you can even set a `height` or `padding-bottom` in percentage referring to the Vueper Slides height for instance (so it will keep ratio when you resize).

If you really have no other way of displaying the content you can still set a height on slide change from an event callback: https://antoniandre.github.io/vueper-slides/#events.

I hope you will find inspiration in these multiple ways to achieve adaptive height for your case.

**Comment by avesus** [comment]
`<vueper-slide
        style="background-size: 100% auto; background-position: center; background-repeat: no-repeat;" ... />`
