### ISSUE TITLE
Images from slider aren't showing from a Netlify static deployment

### ISSUE THREAD

**Issue by jalasem** [antoniandre/vueper-slides#82]
Hello,

I add the slider to my app, my paths are correct, on the network tab it loads fine but all I am seeing is 1234 on the website when I pushed it to Netlify

## How to reproduce the error
- Create a nuxt app
- add vueper-slide to the code as directed in the documentation
- run yarn generate
- use any type of local server to serve the *dist* folder or push the dist folder online.
- *Anomaly:* You will see 1234 (depending on the number of slides) instead of the real slide you were seeing in dev

**Comment by jalasem** [comment]
@antoniandre, please respond

**Comment by KerneggerTim** [comment]
@jalasem, did you find a solution or work around?

**Comment by jalasem** [comment]
Nope
I had to implement it myself

**Comment by antoniandre** [comment]
Hi @jalasem & @KerneggerTim,

I answered the same issue here https://github.com/antoniandre/vueper-slides/issues/86, sorry if it's too late for you.
Please continue the thread there if not solved.
