### ISSUE TITLE
Images blank in nuxt

### ISSUE THREAD

**Issue by soyjonathanespinosa** [antoniandre/vueper-slides#86]
I am using Nuxt, and in development are working fine but when I do nuxt generate, the images in production are blank, in inspect the images are there, slider still working, but I just see a blank slider.

Could you please help me?

Thank you

**Comment by antoniandre** [comment]
Hi @soyjonathanespinosa,

Sorry I missed your issue!
Just adding some info here anyway, for the next reader.

This come from the way you add the images path in Nuxt.

There are multiple ways to link to your images, and it's different if your image is in the `assets/` folder or in the `public/` directory. 
Assuming your image is in `public/` for instance, one way is: 

```js
data: () => ({
   baseUrl: process.env.BASE_URL,
   // Or this simpler version:
   // baseUrl: 'https://my-website.com/'
})
```

```html
:image="`${baseUrl}images/my-image.jpg`"
```

Cheers.
