### ISSUE TITLE
Add Zoom in / out

### ISSUE THREAD

**Issue by vespadj** [antoniandre/vueper-slides#88]
Please add a Zoom in and Zoom out function, for example like attachments in Gmail.
Thanks

**Comment by claytongf** [comment]
Any way to get this feature?
I've tried with another zoom component but it doesn't work

**Comment by vespadj** [comment]
as workaround, I put picture in a <img> , so in Firefox, right click on picture, Shift+Show Picture (I don't know the correct translation) to open picture in a new tab and use native zoom of Firefox.

**Comment by antoniandre** [comment]
Hi, sorry for late reply.
This feature will not be added but you can do this fairly easily when using custom slide content.
1. set a `slide-ratio`
2. use the `<vueper-slide>`'s `content` slot and add the slide image yourself
3. attach click event and style the modal with CSS. nowadays it's very easy using flexbox for vertical centering.

@vespadj way also works.
