### ISSUE TITLE
First image in dynamic gallery still appearing at the end

### ISSUE THREAD

**Issue by vespadj** [antoniandre/vueper-slides#89]
**Scenario**
_appvue.$data.slides_  array of pictures is changed during browsers of the site

**Bug**
The first image that initialise the vueper for the first time is still displayed for a bit second at the end of the slides, after you change _appvue.$data.slides_ programmatically

**Workaround**
I init the vue component with this:
` slides: [ {image: 'img/blank.png'} ]`
so a white image is initilized

**Comment by antoniandre** [comment]
Hi @vespadj,

Can you try this example and let me know if it fixes your use case? this is version 2.8.6.
In this example, the slides are added after init, 1 by 1 every 2 seconds.
https://codepen.io/antoniandre/pen/ZEbgBjy?editors=1010

Hope it helps.

**Comment by vespadj** [comment]
Hi @antoniandre ,
it doesn't fix.
To replicate the behaviour delete or replace the first image after a few second.
Anyway I resolve well with the workaround at the first post.
Also, I like arrows on edge.

Thanks

**Comment by antoniandre** [comment]
@vespadj, it depends a lot on your vueperslides setup.

I tried removing disable-arrows-on-edges and using slides.shift() on mounted and in a timeout after 2 secs and it works fine.

So if everything is solved for you, you can close the issue, otherwise we can investigate but you need to share your code.

Cheers.

**Comment by vespadj** [comment]
Hi @antoniandre ,
test here: [https://codepen.io/vespadj/pen/jOWEKrv](https://codepen.io/vespadj/pen/jOWEKrv)

**Comment by antoniandre** [comment]
Hi @vespadj, 
Thanks for the Codepen, it was quite helpful to understand the problem.
It was a tricky bug, but it should now be solved in version 2.9.2.

Your Codepen works now (make sure you put the right Vueper Slides version in the settings).

Let me know if you still have an issue.

**Comment by vespadj** [comment]
ok
