### ISSUE TITLE
When single slide added alongside array of slide it appears twice

### ISSUE THREAD

**Issue by ManEatingFish** [antoniandre/vueper-slides#90]
I have added a single slide alongside an array of slides and the single slide is added at the beginning and end

### Single Slide added to the vueper-slides instance
    <vueper-slide class="slide">
      <template v-slot:content>
       <div class="opaque slide_inner fl fld-col flai-c pd-16 pds-24">
            <inline-svg class="ident_logo mgb-8" src="svg/logos/ident_logo.svg" style="height:112px"></inline-svg>
            <div class="ts-lg ta-c mgb-16">How does Help My Street work?</div>
            <div class="ts-md ta-c mgb-16">Here is an example...</div>
        </div>
      </template>
    </vueper-slide>

### Multiple Slide added to the same vueper-slides instance

    <vueper-slide v-for="story in stories" :key="story.id" class="slide">
      <template v-slot:content>
       <div class="opaque slide_inner fl fld-col flai-c pd-16 pds-24">
          <textlabel :label="story.text" class="ta-c ts-md mgb-16">{{story.text}}</textlabel>
          <inline-svg class="storyImg" :src="story.image"></inline-svg>
        </div>
      </template>
    </vueper-slide>
  </vueper-slides>

### Example
[Codepen](https://codepen.io/2Martyrs/pen/Yzymddr)

**Comment by antoniandre** [comment]
Hi @ManEatingFish,
Thanks for reporting.
This has never been implemented, it is now, in version 2.9.0.
In your Codepen make sure to hit the right version of Vueper Slides on the CDN. I tried and it is working as expected now.

Hope it helps. Let me know if there is still an issue.
