### ISSUE TITLE
First slide appears at n+1 place. Bug or feature?

### ISSUE THREAD

**Issue by rucebee** [antoniandre/vueper-slides#95]
"vueperslides": "^2.8.6"
At trivial use case I have undesired three slides. 1st === 3rd
Why?
```
<vueper-slides fixed-height="true">
  <vueper-slide image="/images/quest-fairy-1.jpg"/>
  <vueper-slide image="/images/quest-fairy-2.jpg"/>
</vueper-slides>
```

**Comment by antoniandre** [comment]
Hi @rucebee,
Thanks for reporting.
This is a bug and feature at the same time, expected behavior but never been implemented before!
It is now, in version 2.9.0.

Please try and let me know if there is still an issue.

**Comment by rucebee** [comment]
2.9.0 the issues is fixed. thank you for prompt action))

I could not figure out another misbehaviour on my page, but now I'm pretty sure - it is because of vueperslides
Please, check this out
https://github.com/antoniandre/vueper-slides/issues/96
