### ISSUE TITLE
prevent screen to scroll to component on goToSlide

### ISSUE THREAD

**Issue by woshitom** [antoniandre/vueper-slides#97]
going to slide on not visible vueper-slides will scroll the Y axe to its position. How can I prevent such scroll?
I'm trying to sync multiple instances and this auto scroll is not convenient in a UI point of view. For example in https://antoniandre.github.io/vueper-slides/ in the "Sync 2 instances" exemple, moving the top vueper-slides when the bottom vueper-slides is not visible on screen will trigger a scroll to the bottom vueper-slides, I'd like to prevent that
![ezgif-4-655db8246054](https://user-images.githubusercontent.com/7259389/86518749-f7fcd780-be5d-11ea-8c4e-de2b3ee27d1a.gif)

**Comment by woshitom** [comment]
I found a fix:
add this before starting to moveToSlide:

```
var x=window.scrollX;
var y=window.scrollY;
window.onscroll=function(){window.scrollTo(x, y);};
```

add this after the last vueper-slides had move to slide:

`setTimeout(function(){ window.onscroll=function(){}; }, 10);`

**Comment by antoniandre** [comment]
Thanks for sharing your point of view and workaround @woshitom.

I have integrated a solution based on the same idea in version 2.10.8 so you don't have to worry about it anymore. ;)

Hope it helps.

**Comment by antoniandre** [comment]
I am closing this issue now, please reopen if not solved!
